### ISSUE TITLE
Error at Trinity best transcript set

### ISSUE THREAD

**Issue by manuelsmendoza** [trinityrnaseq/trinity_community_codebase#2]
Hi!

I'm trying to use the Trinity best transcript set guide but i've the following errror. Does anyone know what is happening? 

```
$ trinity_cdhit_feeder.pl -infile non-rRNA_Trinity.fasta.transdecoder.pep -output Transcriptome.fasta.transdecoder.pep_pass1 -tmp_dir ./tmp -max_children 40 -params -b 180 > cdhit_feeder.log
2019-03-26 19:05:51
Command line arguments were infile: non-rRNA_Trinity.fasta.transdecoder.pep output: Transcriptome.fasta.transdecoder.pep_pass1 tmp_dir: ./tmp max_children: 40 params: -b
could not open ./tmp/job_1_out
```

Thanks in advance,
~MM.

**Comment by mathog** [comment]
On 26-Mar-2019 11:12, Manuel Mendoza wrote:
> Hi!
> 
> I'm trying to use the Trinity best transcript set guide but i've the
> following errror. Does anyone know what is happening?
> 
> ```
> $ trinity_cdhit_feeder.pl -infile
> non-rRNA_Trinity.fasta.transdecoder.pep -output
> Transcriptome.fasta.transdecoder.pep_pass1 -tmp_dir ./tmp
> -max_children 40 -params -b 180 > cdhit_feeder.log
> 2019-03-26 19:05:51
> Command line arguments were infile:
> non-rRNA_Trinity.fasta.transdecoder.pep output:
> Transcriptome.fasta.transdecoder.pep_pass1 tmp_dir: ./tmp
> max_children: 40 params: -b
> could not open ./tmp/job_1_out
> ```

That is my script.  The time stamp on my current version is Oct 19 
11:28, if yours is older than that let me know and I will upload a new 
release.

This could be a disk space or directory protection problem.  Be sure 
that the account which is running can read/write in ./tmp.  Be sure the 
disk isn't out of space.

If that isn't it, modify the script and change line 35 to:

$dbglvl=4

clean out ./tmp and run it again.  Tell me what it says. Also let me 
know at least in summary what is in ./tmp.

You may email me directly, the details of this debugging are going to 
clutter up this list and the only thing that really needs to be posted 
is the final resolution.

Regards,

David Mathog
mathog@caltech.edu
Manager, Sequence Analysis Facility, Biology Division, Caltech

**Comment by mathog** [comment]
On 26-Mar-2019 11:12, Manuel Mendoza wrote:
> Hi!
> 
> I'm trying to use the Trinity best transcript set guide but i've the
> following errror.

Also, check that you modified the script properly.  The $CDHIT binary
path as distributed is for my home system.  The script should have 
caught
that though because the -x test should have failed.

#BEFORE modification!
cksum trinity_cdhit_feeder.pl
2102552423 4885 trinity_cdhit_feeder.pl
wc -l trinity_cdhit_feeder.pl
167 trinity_cdhit_feeder.pl

Regards,

David Mathog
mathog@caltech.edu
Manager, Sequence Analysis Facility, Biology Division, Caltech

**Comment by manuelsmendoza** [comment]
Problem solved...

So sorry, it was not related with your script @mathog. It wasn't passing properly the `$CDH_BAND` variable. Finally, I've solved it by passing directly this command i.e. `-params "-b 180"`.

Thanks so much,
~MM

**Comment by mathog** [comment]
On 26-Mar-2019 12:14, Manuel Mendoza wrote:
> Problem solved...
> 
> So sorry, it was not related with your script @mathog. It wasn't
> passing properly the `$CDH_BAND` variable. Finally, I've solved it by
> passing directly this command i.e. `-params "-b 180"`.

In the instructions it currently says:

nice trinity_cdhit_feeder.pl \
   -infile Transcriptome.fasta.transdecoder.pep \
   -output Transcriptome.fasta.transdecoder.pep_pass1 \
   -tmp_dir /tmp/tmpfeed -max_children 40 -params $CDH_BAND 
 >cdhit_feeder.log 2>&1 &

Apparently it should be instead:

nice trinity_cdhit_feeder.pl \
   -infile Transcriptome.fasta.transdecoder.pep \
   -output Transcriptome.fasta.transdecoder.pep_pass1 \
   -tmp_dir /tmp/tmpfeed -max_children 40 -params "$CDH_BAND" 
 >cdhit_feeder.log 2>&1 &

Does the second form work for you?

Regards,

David Mathog
mathog@caltech.edu
Manager, Sequence Analysis Facility, Biology Division, Caltech

**Comment by manuelsmendoza** [comment]
It's worked! Thanks!!

**Comment by shzadiqbal** [comment]
hi 
i am facing an error while running this pipeline
 cat keep_these | fastaselecth -sel- -in merge.fasta >Transcriptome_reduced.fasta 
fastaselecth: fatal error: duplicate entry names in list, alternate header terminators may be needed
please help me to solve this. All other previous pipeline ran smoothly till now.
